const data = {
    "city": {
    "id": 1007698,
    "city": "Berlin",
    "lat": 52.52,
    "lon": 13.38,
    "state": "",
    "country": "de",
    "zip": "meetup1",
    "member_count": 2374
    },
    "events": [
    {
    "created": 1618308469000,
    "duration": 10800000,
    "id": "277541034",
    "name": "PyBerlin 28 - 🌷 Spring event 🌷",
    "rsvp_limit": 240,
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1621873800000,
    "local_date": "2021-05-24",
    "local_time": "18:30",
    "updated": 1619081618000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 40,
    "venue": {
    "id": 26906060,
    "name": "Online event",
    "repinned": false,
    "country": "",
    "localized_country_name": ""
    },
    "is_online_event": true,
    "group": {
    "created": 1544283736000,
    "name": "PyBerlin",
    "id": 30671970,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "PyBerlin",
    "who": "Pythonistas",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/PyBerlin/events/277541034/",
    "description": "<p>Agenda:</p> <p>• 18:30 - Welcome to PyBerlin! // Organisers</p> <p>• 18:35 - Retro Gamedev: Making your own compiled language for NES in Python // Ivan Nikolaev</p> <p>Talk description:<br/>Mid-80s. The game industry was relaunched with the release of Nintendo Entertainment System, the 8-bit console which defined gaming for the decade to follow.<br/>For its time, it was quite a piece of hardware, featuring the legendary 6502 CPU, 2KiB RAM, and a "GPU" capable of rendering a bunch of sprites on a 256x240 pixels TV screen.<br/>How do you ever make a game with that?! Back in time, it was a raw assembly and thinking by hex numbers.</p> <p>In this talk, Ivan will show you how the NES worked and how to develop games for it. But to keep your sanity in place, there'll be almost no coding in assembly.</p> <p>Instead, you will learn how to create your own programming language, write a compiler for it in Python and make the game development for NES fun!</p> <p>Ivan will show how to define and parse the language's grammar, translate the high-level constructs into low-level instructions, compile them into NES-compatible machine code and build the final game executable which goes into the ROM.</p> <p>Press "start" to continue!</p> <p>Speaker's bio:<br/>Ivan became a programmer, driven by his childhood dream of making video games. During a long journey through software development, he made his bones in the wasteland of system, web and desktop applications. Ivan's dream came true three years ago, when he joined Wargaming and became a part of the awesome team behind the legendary World of Tanks game. Ivan is currently developing the gameplay logic for it.</p> <p>• 19:15 - Short break</p> <p>• 19:20 - TBA // TBA</p> <p>• 20:00 - A slice of Python? // Naomi Ceder</p> <p>Talk description:<br/>In Python, slices are a powerful way to manipulate lists and some other sequence types. But what are a slices really? And how do they do their magic? We'll spend 30 minutes live coding simple experiments to see what a slice is, how they work, and even some a slice's cooler tricks. Anyone who knows what a slice is will come away with a deeper understanding of this Python feature.</p> <p>Speaker's bio:<br/>Naomi Ceder earned a Ph.D in Classics several decades ago, but switched from ancient human languages to computer languages sometime in the last century. Since 2001, she has been learning, teaching, writing about, and using Python. Naomi is the immediate past chair the Python Software Foundation board of directors. She also speaks internationally about the Python community, and on inclusion and diversity in technology in general. By day she leads a team of Python programmers for Dick Blick Art Materials, and in her spare time she enjoys sketching, knitting, and deep philosophical conversations with her dog.</p> <p>• 20:40 - Closing session // Organisers</p> <p>Link to this event will be provided by organisers closer to the event.</p> ",
    "visibility": "public",
    "pro_is_email_shared": false,
    "member_pay_fee": false
    },
    {
    "created": 1564344336000,
    "duration": 7200000,
    "id": "jbrsfryccjbfc",
    "name": "Berlin Perl Mongers",
    "rsvp_limit": 12,
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1625072400000,
    "local_date": "2021-06-30",
    "local_time": "19:00",
    "updated": 1603824306000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 1,
    "venue": {
    "id": 26540259,
    "name": "none",
    "lat": 52.5200080871582,
    "lon": 13.404953956604004,
    "repinned": true,
    "address_1": "none",
    "city": "Berlin",
    "country": "de",
    "localized_country_name": "Germany"
    },
    "is_online_event": false,
    "group": {
    "created": 1477574555000,
    "name": "Berlin Perl Mongers",
    "id": 20927378,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "Berlin-Perl-Mongers",
    "who": "Mongers",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/Berlin-Perl-Mongers/events/jbrsfryccjbfc/",
    "description": "<p>Wir treffen uns jedesmal an einem anderen Ort. Das Restaurant wird kurzfristig bekanntgegeben (3-5 Tage vorab).</p> ",
    "how_to_find_us": "https://berlin.pm.org",
    "visibility": "public",
    "member_pay_fee": false
    },
    {
    "created": 1515424197000,
    "duration": 10800000,
    "id": "bcvtkrycchbbc",
    "name": "Informal get-together of Kotlin developers in Berlin",
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1621530000000,
    "local_date": "2021-05-20",
    "local_time": "19:00",
    "updated": 1572729816000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 4,
    "is_online_event": false,
    "group": {
    "created": 1479909210000,
    "name": "Kotlin User Group Berlin",
    "id": 21262742,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "kotlin-berlin",
    "who": "Kotlin fans",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/kotlin-berlin/events/bcvtkrycchbbc/",
    "description": "<p>Line-up: TBA</p> ",
    "visibility": "public",
    "member_pay_fee": false
    },
    {
    "created": 1515424197000,
    "duration": 10800000,
    "id": "bcvtkryccjbwb",
    "name": "Informal get-together of Kotlin developers in Berlin",
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1623949200000,
    "local_date": "2021-06-17",
    "local_time": "19:00",
    "updated": 1572729816000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 3,
    "is_online_event": false,
    "group": {
    "created": 1479909210000,
    "name": "Kotlin User Group Berlin",
    "id": 21262742,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "kotlin-berlin",
    "who": "Kotlin fans",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/kotlin-berlin/events/bcvtkryccjbwb/",
    "description": "<p>Line-up: TBA</p> ",
    "visibility": "public",
    "member_pay_fee": false
    },
    {
    "created": 1515424197000,
    "duration": 10800000,
    "id": "bcvtkrycckbtb",
    "name": "Informal get-together of Kotlin developers in Berlin",
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1626368400000,
    "local_date": "2021-07-15",
    "local_time": "19:00",
    "updated": 1572729817000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 3,
    "is_online_event": false,
    "group": {
    "created": 1479909210000,
    "name": "Kotlin User Group Berlin",
    "id": 21262742,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "kotlin-berlin",
    "who": "Kotlin fans",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/kotlin-berlin/events/bcvtkrycckbtb/",
    "description": "<p>Line-up: TBA</p> ",
    "visibility": "public",
    "member_pay_fee": false
    },
    {
    "created": 1618754428000,
    "duration": 7200000,
    "id": "277644388",
    "name": "PyBerlin 29 - ☀️☀️ Summer event ☀️☀️",
    "rsvp_limit": 240,
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1624294800000,
    "local_date": "2021-06-21",
    "local_time": "19:00",
    "updated": 1618842211000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 20,
    "venue": {
    "id": 26906060,
    "name": "Online event",
    "repinned": false,
    "country": "",
    "localized_country_name": ""
    },
    "is_online_event": true,
    "group": {
    "created": 1544283736000,
    "name": "PyBerlin",
    "id": 30671970,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "PyBerlin",
    "who": "Pythonistas",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/PyBerlin/events/277644388/",
    "description": "<p>Agenda:</p> <p>• 19:00 - Welcome to PyBerlin! // Organisers</p> <p>• 19:10 - TBA // TBA</p> <p>• 19:50 - Short break</p> <p>• 20:00 - TBA // TBA</p> <p>• 20:40 - Closing session // Organisers</p> <p>Link to this event will be provided by organisers closer to the event.</p> ",
    "visibility": "public",
    "pro_is_email_shared": false,
    "member_pay_fee": false
    },
    {
    "created": 1599659306000,
    "duration": 28800000,
    "id": "pzglxryccgbkc",
    "name": "Corona: SUSPENDED!!!! FreeCodeCamp CoLearning/CoWorking",
    "rsvp_limit": 3,
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1619510400000,
    "local_date": "2021-04-27",
    "local_time": "10:00",
    "updated": 1599659306000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 3,
    "venue": {
    "id": 25490225,
    "name": "In-Berlin",
    "lat": 52.534488677978516,
    "lon": 13.358409881591797,
    "repinned": true,
    "address_1": "Lehrter Straße 53",
    "city": "Berlin",
    "country": "de",
    "localized_country_name": "Germany"
    },
    "is_online_event": false,
    "group": {
    "created": 1505369195000,
    "name": "FreeCodeCamp Berlin",
    "id": 25919262,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "FreeCodeCamp-Berlin",
    "who": "Camper",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/FreeCodeCamp-Berlin/events/pzglxryccgbkc/",
    "description": "<p>Open CoWorking/CoLearning; Work on the FreeCodeCamp curriculum, your own project or what ever you want to work on.</p> <p>Note: until further notice, our meetups are restricted by governmental regulations and our safety concerns. We will keep you updated by email here when we go back to normal.</p> <p>Meanwhile use:</p> <p>Forum: <a href="https://www.freecodecamp.org/forum/" class="linkified">https://www.freecodecamp.org/forum/</a></p> <p>Chats:<br/><a href="https://t.me/FreeCodeCampBerlin" class="linkified">https://t.me/FreeCodeCampBerlin</a><br/><a href="https://discord.gg/SVb44D9" class="linkified">https://discord.gg/SVb44D9</a></p> <p>Down below are out-dated information, for the meetups in person, just kept for information what we are (supposedly ) doing here .... once the Apocalypse is over ;-)</p> <p>Stay safe!</p> <p>Just drop in!<br/>There is fast internet, power, snacks, beverages, a sofa, and a nice atmosphere. :-)</p> <p><img src="https://secure.meetupstatic.com/photos/event/3/c/1/600_464520961.jpeg" /></p> <p>FAQ:<br/>Q: What do I need to know?<br/>A: Just come as you are. No prior programming knowledge required.</p> <p>Q: Are there any costs?<br/>A: No, attending does not incur any costs. You can get coffee or water for free. Other beverages (like beer, coke, mate, etc.) are 1€/bottle, snacks (like snickers, chocolate, etc.) are available for 0,25€/0,5€.</p> <p>Q: Is it colearning or coworking?<br/>A: It is more colearning, i.e. we help each other.<br/>"coworking" would be more like a "paid space",<br/>i.e. you'd pay for being there and its services.</p> <p>Q: What is this space?<br/>A: The space is the rooms of in-berlin.de -<br/>a community Internet Service Provider (ISP).<br/>There are other meetups happening here, like the Berlin Linux User Group (BeLUG) or the electronics laboratory<br/>(eLAB).</p> <p>Q: Can I host my own event in this space?<br/>A: Take a look at the VereinsRaum calendar<br/><a href="http://vrkalender.in-berlin.de" class="linkified">http://vrkalender.in-berlin.de</a><br/>for a free time slot - and then<br/>contact IN-Berlin's support team:<br/>support@in-berlin.de<br/>as long as the cause of your meetup<br/>if for everyone and it's non-profit.</p> ",
    "how_to_find_us": "The entrance is on the ground floor at the door between the two large windows (BeLUG+IN-Berlin). You can't miss it ...",
    "visibility": "public",
    "member_pay_fee": false
    },
    {
    "created": 1614792808000,
    "duration": 7200000,
    "id": "276714434",
    "name": "PyBerlin 27 - 🌷  Spring is here event 🌷",
    "rsvp_limit": 240,
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1619456400000,
    "local_date": "2021-04-26",
    "local_time": "19:00",
    "updated": 1615108187000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 98,
    "venue": {
    "id": 26906060,
    "name": "Online event",
    "repinned": false,
    "country": "",
    "localized_country_name": ""
    },
    "is_online_event": true,
    "group": {
    "created": 1544283736000,
    "name": "PyBerlin",
    "id": 30671970,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "PyBerlin",
    "who": "Pythonistas",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/PyBerlin/events/276714434/",
    "description": "<p>Agenda:</p> <p>• 19:00 - Welcome to PyBerlin! // Organisers</p> <p>• 19:10 - Batteries Included: Things you can do with standard libraries // Cheuk Ting Ho</p> <p>Talk description:<br/>Any Python user knows the power of Python is having many packages in PyPI that you can simply pip install. Imagine pip is not allowed at work due to security issues. Don’t worry! You can still do many things with the standard libraries included. Let me show you those that you should know and use.</p> <p>Speaker's bio:<br/>After having a career in data science, Cheuk now brings her knowledge in data and passion for the tech community into TerminusDB as the developer relations lead. Cheuk constantly contributes to the open-source community by giving free tutorials on Twitch and organize sprints to encourage diversity contributions.</p> <p>• 19:50 - Short break</p> <p>• 20:00 - Corona Virus Computations and Plots using Python Notebooks in Google Colab // Gerald Schuller</p> <p>Talk description:<br/>In early 2020 I wrote Python programs of the Corona virus spread for predicting if conferences will be taking place in presence or not, using simple models and “live” data from the Johns Hopkins Github repository. Later I ported them to Jupyter notebooks in Google Colab, hosted in Github. In the talk I will show my prediction models, and their implementation with interactive plots in Colab.<br/>Website for it: <a href="https://github.com/TUIlmenauAMS/CoronaComputationPrograms" class="linkified">https://github.com/TUIlmenauAMS/CoronaComputationPrograms</a><br/><a href="https://www.tu-ilmenau.de/en/applied-media-systems-group/climate-change-calculated/" class="linkified">https://www.tu-ilmenau.de/en/applied-media-systems-group/climate-change-calculated/</a></p> <p>Speaker's bio:<br/>Gerald Schuller is Professor at Ilmenau University of Technology in Media Technology, Group of Applied Media Systems.He is interested in machine learning for audio and robots, and likes programming in Python :-).</p> <p>• 20:40 - Closing session // Organisers</p> <p>Link to this event will be provided by organisers closer to the event.</p> ",
    "visibility": "public",
    "pro_is_email_shared": false,
    "member_pay_fee": false
    },
    {
    "created": 1618772296000,
    "duration": 10800000,
    "id": "277649827",
    "name": "OKR Open Space Event",
    "rsvp_limit": 130,
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1620133200000,
    "local_date": "2021-05-04",
    "local_time": "15:00",
    "updated": 1618772641000,
    "utc_offset": 7200000,
    "waitlist_count": 0,
    "yes_rsvp_count": 13,
    "is_online_event": false,
    "group": {
    "created": 1567169501000,
    "name": "OKRs AT THE CENTER - Virtual Meetup for OKR practitioners",
    "id": 32696797,
    "join_mode": "approval",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "OKR-Remote-English",
    "who": "OKR Practitioner",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/OKR-Remote-English/events/277649827/",
    "description": "<p>You want to learn more about OKRs from fellow OKR practitioners? Or discuss a question that has been on your mind for a long time? Or you would like to experience the format of an Open Space first hand?</p> <p>Join us for the OKR Open Space Event on May 4th!</p> <p>What is an Open Space?</p> <p>The main principle of Open Space Events is “self-organization”. It is a participant-driven and agendaless unconference. Our overall theme and focus is OKRs. You as a participant decide what you want to talk about, explore, share or discuss about OKRs. Participants contribute with their sessions and again participants choose which sessions to visit.</p> <p>Register through Eventbrite (free) to save your spot: <a href="https://www.eventbrite.de/e/okr-open-space-tickets-149676702045" class="linkified">https://www.eventbrite.de/e/okr-open-space-tickets-149676702045</a></p> <p>We are looking forward to connecting, sharing and learning with you!</p> <p>Natalija &amp; Cansel</p> ",
    "visibility": "public",
    "member_pay_fee": false
    },
    {
    "created": 1534878992000,
    "duration": 10800000,
    "id": "253983580",
    "name": "⚛ React.js & React Native Berlin Meetup ",
    "rsvp_limit": 120,
    "date_in_series_pattern": false,
    "status": "upcoming",
    "time": 1619542800000,
    "local_date": "2021-04-27",
    "local_time": "19:00",
    "updated": 1602538679000,
    "utc_offset": 7200000,
    "waitlist_count": 433,
    "yes_rsvp_count": 120,
    "venue": {
    "id": 24804184,
    "name": "Berlin Mitte, Address will be announced ",
    "lat": 52.522186279296875,
    "lon": 13.409331321716309,
    "repinned": true,
    "address_1": "10178",
    "city": "Berlin",
    "country": "de",
    "localized_country_name": "Germany"
    },
    "is_online_event": false,
    "group": {
    "created": 1472904792000,
    "name": "React.js & React Native Berlin",
    "id": 20383485,
    "join_mode": "open",
    "lat": 52.52000045776367,
    "lon": 13.380000114440918,
    "urlname": "ReactJS-and-React-Native-Berlin",
    "who": "Members",
    "localized_location": "Berlin, Germany",
    "state": "",
    "country": "de",
    "region": "en_US",
    "timezone": "Europe/Berlin"
    },
    "link": "https://www.meetup.com/ReactJS-and-React-Native-Berlin/events/253983580/",
    "description": "<p>Join our React.js &amp; React Native Berlin Meetup, Germany’s largest ReactJS Meetup</p> <p>Get the newest information, quality networking, get inspired, exchange ideas and insights about React.JS and React Native and join our participants: founder, CTOs, Android, iOS and Javascript developer from the top corporates and startups now at our event.</p> <p>To ensure the quality of participates for creating the same like-minded networking ambiance for everybody, and growing high-quality participants who really like to come and for our organizational team, we take our members’ suggestion to offer a sign-up fee to make it fair for everyone who really wants to come. Preventing no showing ups occupying our limited vacancies, which should be fairly provided to our members who sincerely like to join and have a great time to share knowledge in a happy atmosphere.</p> <p>We have again awesome speakers.</p> <p>19.00 -19.30: Arrivals &amp; Networking</p> <p>19.30 - 19.35: Introduction by Atlassian &amp; Markus Lühmann, Founder of Digital Creators and Galaxonic</p> <p>19:35 - 21.05: Talks &amp; Q&amp;A</p> <p>21.00 - 22.00: Mingle &amp; Networking</p> <p>Feedback or anything to share, contact us: react@digital-creators.de</p> ",
    "visibility": "public",
    "member_pay_fee": false
    }
    ]
    }
    